#!/usr/bin/env python3
"""Generate responsive-image variants for site photos.

For every source image under the configured directories, generates a set of
smaller width buckets (in the original format, for broad compatibility) plus
matching WebP versions, and records which buckets exist per image in
_data/img_variants.yml so Liquid templates/includes can build correct
srcset/<picture> markup without guessing which files exist.

Skips: files that are already-generated variants (matched by the
"-<width>w" naming suffix), non-raster files, and any source whose variant
is already newer than the source (so repeat runs are fast / a no-op).

Usage: python3 scripts/resize_images.py [dir ...]
  (defaults to the directories in DEFAULT_DIRS if none given)
"""
import os
import re
import sys

from PIL import Image

DEFAULT_DIRS = [
    "images",  # top-level only (os.listdir is non-recursive) -- group photos etc.
    "images/teampic",
    "images/pubpic",
    "images/coverart",
    "images/newspic",
    "images/eventspic",
    "images/carousel",
]
WIDTHS = [400, 800, 1600]
RASTER_EXTS = {".jpg", ".jpeg", ".png"}
VARIANT_RE = re.compile(r"-(\d+)w$")
MANIFEST_PATH = "_data/img_variants.yml"


def is_source_image(path):
    stem, ext = os.path.splitext(os.path.basename(path))
    if ext.lower() not in RASTER_EXTS:
        return False
    if VARIANT_RE.search(stem):
        return False  # this IS a generated variant, not a source
    return True


def variant_path(path, width, ext_override=None):
    root, ext = os.path.splitext(path)
    ext = ext_override or ext
    return f"{root}-{width}w{ext}"


def needs_regen(src, dst):
    if not os.path.exists(dst):
        return True
    return os.path.getmtime(src) > os.path.getmtime(dst)


def process_image(path, manifest):
    with Image.open(path) as im:
        orig_w, orig_h = im.size
        im = im.convert("RGB") if im.mode not in ("RGB", "RGBA") else im

        widths_here = [w for w in WIDTHS if w < orig_w]
        generated = []
        for w in widths_here:
            h = round(orig_h * w / orig_w)

            same_fmt_dst = variant_path(path, w)
            webp_dst = variant_path(path, w, ext_override=".webp")

            if needs_regen(path, same_fmt_dst) or needs_regen(path, webp_dst):
                resized = im.resize((w, h), Image.LANCZOS)
                save_kwargs = {"quality": 85} if path.lower().endswith((".jpg", ".jpeg")) else {}
                resized.save(same_fmt_dst, **save_kwargs)
                resized.save(webp_dst, "WEBP", quality=82)
                print(f"  generated {same_fmt_dst}, {webp_dst}")

            generated.append(w)

        manifest[path] = {"width": orig_w, "height": orig_h, "variants": generated}


def main():
    dirs = sys.argv[1:] or DEFAULT_DIRS
    manifest = {}
    for d in dirs:
        if not os.path.isdir(d):
            continue
        for fname in sorted(os.listdir(d)):
            path = os.path.join(d, fname)
            if not os.path.isfile(path) or not is_source_image(path):
                continue
            print(f"{path}")
            process_image(path, manifest)

    os.makedirs(os.path.dirname(MANIFEST_PATH), exist_ok=True)
    with open(MANIFEST_PATH, "w") as f:
        f.write("# Auto-generated by scripts/resize_images.py -- do not hand-edit.\n")
        for path in sorted(manifest):
            info = manifest[path]
            f.write(f"{path}:\n")
            f.write(f"  width: {info['width']}\n")
            f.write(f"  height: {info['height']}\n")
            f.write(f"  variants: [{', '.join(str(w) for w in info['variants'])}]\n")
    print(f"\nWrote manifest for {len(manifest)} images to {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
